# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: no
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: no
    ports:
      - 8080:8080